// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz-A7OU7sxAGxBMuIo3Gjocl-TpnPBpjQ',
    appId: '1:67417231973:web:21439d09794f10bef2ec8c',
    messagingSenderId: '67417231973',
    projectId: 'ibeehc-d4069',
    authDomain: 'ibeehc-d4069.firebaseapp.com',
    storageBucket: 'ibeehc-d4069.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqEI2f6UF-Legi2KqJHbmWChcMUPgRhSg',
    appId: '1:67417231973:android:8bab1b3ac254cccef2ec8c',
    messagingSenderId: '67417231973',
    projectId: 'ibeehc-d4069',
    storageBucket: 'ibeehc-d4069.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjhA4VQMv0SEU4m0Oq1uGXxBKWjU9yV0g',
    appId: '1:67417231973:ios:67a4d9e95780e241f2ec8c',
    messagingSenderId: '67417231973',
    projectId: 'ibeehc-d4069',
    storageBucket: 'ibeehc-d4069.appspot.com',
    androidClientId: '67417231973-2no2vr06k7ls0nib4os9n72inupv1jbm.apps.googleusercontent.com',
    iosClientId: '67417231973-rkgkiqb4h7l68cd4ebhfb5tifemdt2lp.apps.googleusercontent.com',
    iosBundleId: 'com.example.ibMed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjhA4VQMv0SEU4m0Oq1uGXxBKWjU9yV0g',
    appId: '1:67417231973:ios:c8a02dea468530f7f2ec8c',
    messagingSenderId: '67417231973',
    projectId: 'ibeehc-d4069',
    storageBucket: 'ibeehc-d4069.appspot.com',
    androidClientId: '67417231973-2no2vr06k7ls0nib4os9n72inupv1jbm.apps.googleusercontent.com',
    iosClientId: '67417231973-0s8b98u3pretm64enl107o6sdh32hl7k.apps.googleusercontent.com',
    iosBundleId: 'com.example.ibMed.RunnerTests',
  );
}
